# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown

title: 侯志强
description: 一个软件开发工程师
author:
  name: 侯志强
  email: hzq1988abc@gmail.com
  github: hzq1988a
  twitter: hzq1988a
  pinterest: asd123
  linkedin: asd123
  bio: 一个软件开发工程师
  email_md5: 614545eaa73d3990e68a16f792a8e050

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: